from __future__ import annotations

from typing import Any

from chess_anti_engine.encoding._lc0_ext import CBoard

THREAT_DIMS: int
HALFKA_DIMS: int
PACK_VERSION: int
FILE_VERSION: int
HAVE_AVX2: int

# Check-resolver / quiescence constants, exported so a test pins the C values
# rather than a Python restatement of them.
RESOLVER_EVAL_CLAMP: int
RESOLVER_MATE_BASE: int
RESOLVER_MATE_PLY_STEP: int
RESOLVER_MAX_PLIES: int
RESOLVER_MAX_DEPTH: int
QSEARCH_MAX_PLY: int
QSEARCH_CHECK_PLIES: int

class InCheckError(ValueError):
    """The NNUE evaluation is undefined for a position in check.

    Callers must resolve check nodes recursively (search the evasions, which may
    themselves give check) before asking for a static evaluation; this exception
    is the enforcement backstop for that invariant.
    """

# The value-provider capsule other extensions import to install this evaluator
# on their eval seam, instead of including its header and getting a second copy
# of its kernel flag and weight cache.
value_provider_capsule: object

# The two race arms, published under the same capsule name and ABI. Both resolve
# check nodes recursively before evaluating; they differ only in what happens at
# a resolved non-check node (static NNUE vs tactical quiescence).
static_arm_capsule: object
qsearch_arm_capsule: object

def load(pack_path: str, /) -> object: ...
def set_simd(enabled: bool, /) -> bool: ...
def simd_active() -> bool: ...
def weight_cache_size() -> int: ...
def info(handle: object, /) -> dict[str, Any]: ...
def source_sha256(handle: object, /) -> str: ...
def evaluate(handle: object, board: CBoard, /) -> int: ...
def trace(handle: object, board: CBoard, /) -> tuple[int, tuple[int, ...], tuple[int, ...]]: ...
def active_features(
    board: CBoard, perspective: int, /
) -> tuple[tuple[int, ...], tuple[int, ...]]: ...
def benchmark(
    handle: object, boards: list[CBoard], repeats: int, threads: int, /
) -> tuple[int, float, int]: ...
def provider_eval(name: str, weights_path: str, board: CBoard, /) -> int: ...
def provider_names() -> tuple[str, ...]: ...
def set_arm_config(
    resolver_max_depth: int, qsearch_max_ply: int, qsearch_check_plies: int, /
) -> dict[str, int]: ...
def arm_eval(
    name: str, weights_path: str, boards: list[CBoard], /
) -> tuple[list[int], dict[str, int]]: ...
def arm_open(name: str, weights_path: str, /) -> object: ...
def arm_handle_eval(handle: object, boards: list[CBoard], /) -> list[int]: ...
def arm_stats(handle: object, /) -> dict[str, int]: ...

# Canonical structural-position DAG. The object handle owns no Python objects;
# the C side retains the mmap'd NNUE weights independently of the load() capsule.
def dag_open(weights_handle: object, initial_nodes: int = 256, /) -> object: ...
def dag_intern_root(
    handle: object, board: CBoard, /
) -> tuple[int, int | None, bool]: ...
def dag_intern_child(
    handle: object, parent_id: int, action: int, child_board: CBoard, /
) -> tuple[int, int | None, bool]: ...
def dag_lookup(handle: object, board: CBoard, /) -> int | None: ...
def dag_value(handle: object, node_id: int, /) -> int | None: ...
def dag_children(handle: object, node_id: int, /) -> list[tuple[int, int]]: ...
def dag_set_root(handle: object, node_id: int, /) -> None: ...
def dag_mark_expanded(handle: object, node_id: int, /) -> None: ...
def dag_stats(handle: object, /) -> dict[str, int]: ...
def dag_reset(handle: object, /) -> None: ...
