"""Frozen-cohort policy diagnostics and an opt-in TailRL-inspired loss.

No training/search path imports this module. Events are supplied by the caller;
search-promoted moves are a proxy, not verified high-reward chess rollouts.
"""
from __future__ import annotations

import math
from dataclasses import asdict, dataclass
from typing import Any

import torch
from torch import Tensor


@dataclass(frozen=True)
class TailCohort:
    """Define the ruler once using the reference, never the candidate."""

    max_prior: float = 0.01
    min_target: float = 0.02
    min_boost: float = 4.0

    def __post_init__(self) -> None:
        if not 0 < self.max_prior < 1:
            raise ValueError("max_prior must be in (0, 1)")
        if not 0 < self.min_target <= 1:
            raise ValueError("min_target must be in (0, 1]")
        if not math.isfinite(self.min_boost) or self.min_boost <= 1:
            raise ValueError("min_boost must be finite and > 1")


def legal_log_probs(logits: Tensor, legal: Tensor) -> Tensor:
    """Legal-renormalized T=1 policy; retain gradients at very small priors."""
    if logits.ndim != 2 or logits.shape != legal.shape or not logits.numel():
        raise ValueError("logits and legal must be matching nonempty [B, A] tensors")
    if not logits.is_floating_point() or legal.dtype != torch.bool:
        raise ValueError("logits must be floating point and legal must be boolean")
    if logits.device != legal.device:
        raise ValueError("logits and legal must be on the same device")
    if not bool(legal.any(dim=-1).all()):
        raise ValueError("every row must contain a legal move")
    if not bool(torch.isfinite(logits[legal]).all()):
        raise ValueError("legal logits must be finite")
    # FP16/BF16 logsumexp can erase the very tail we are trying to measure.
    work = logits if logits.dtype == torch.float64 else logits.float()
    return work.masked_fill(~legal, -torch.inf).log_softmax(dim=-1)


def normalized_target(target: Tensor, legal: Tensor) -> Tensor:
    """Normalize stored roundoff, but refuse illegal mass/absent labels."""
    if target.shape != legal.shape or target.device != legal.device:
        raise ValueError("target and legal must have matching shapes/devices")
    if not bool(torch.isfinite(target).all()) or bool((target < 0).any()):
        raise ValueError("target must be finite and nonnegative")
    if bool((target.masked_select(~legal) > 1e-6).any()):
        raise ValueError("target has illegal mass: check position/encoding alignment")
    target = target.detach().masked_fill(~legal, 0)
    sums = target.sum(dim=-1, keepdim=True)
    if not bool((torch.isfinite(sums) & (sums > 0)).all()):
        raise ValueError("zero targets are missing labels, not negative evidence")
    return target / sums


def freeze_cohort(
    reference_logits: Tensor, target: Tensor, legal: Tensor,
    spec: TailCohort = TailCohort(),
) -> Tensor:
    """Reference-rare moves promoted by a fixed, current-position search target.

    This does NOT imply actual same-model search rescue: a replay target may
    have been generated by a different checkpoint. Nor is promotion proof of
    tactical correctness. Store the returned mask when banking observations.
    """
    with torch.no_grad():
        logp = legal_log_probs(reference_logits.double(), legal)
        q = normalized_target(target.to(logp.dtype), legal)
        logq = q.clamp_min(torch.finfo(q.dtype).tiny).log()
        # Inclusive boundaries must survive log/normalization roundoff.
        eps = 8 * torch.finfo(logp.dtype).eps
        return (
            legal & (logp <= math.log(spec.max_prior) + eps)
            & (q >= spec.min_target - eps)
            & ((logq - logp) >= math.log(spec.min_boost) - eps)
        ).detach()


def tail_log_mass(logp: Tensor, legal: Tensor, events: Tensor) -> tuple[Tensor, Tensor]:
    """[B,T,A] fixed events -> [B,T] log masses and nonempty-event mask.

    Empty events get a neutral log mass of zero AND a false validity bit.
    Replacing them before logsumexp avoids all-minus-infinity backward NaNs.
    """
    if (
        events.ndim != 3 or events.shape[0] != logp.shape[0]
        or events.shape[2] != logp.shape[1] or events.shape[1] == 0
        or events.dtype != torch.bool or events.device != logp.device
    ):
        raise ValueError("events must be boolean [B, T, A], T > 0, on logits' device")
    if bool((events & ~legal[:, None, :]).any()):
        raise ValueError("an event contains an illegal move")
    valid = events.any(dim=-1)
    safe_events = torch.where(valid[..., None], events, legal[:, None, :])
    mass = logp[:, None, :].masked_fill(~safe_events, -torch.inf).logsumexp(dim=-1)
    return mass, valid


def tail_event_loss(logits: Tensor, legal: Tensor, events: Tensor) -> Tensor:
    """Mean negative log event mass, averaging tails within each eligible row.

    Differentiable single-move proxy for E_threshold[-log P(reward>threshold)].
    It is not the paper's finite-rollout policy-gradient estimator. Callers
    must freeze event definitions/quality labels outside the current update.
    Empty events/rows are excluded; an entirely empty batch gives a connected
    exact zero. This function is NOT wired into the production trainer.
    """
    logp = legal_log_probs(logits, legal)
    mass, valid = tail_log_mass(logp, legal, events)
    counts = valid.sum(dim=-1)
    per_row = -(mass * valid).sum(dim=-1) / counts.clamp_min(1)
    return per_row.sum() / (counts > 0).sum().clamp_min(1)


def finite_tail_loss(
    logits: Tensor, legal: Tensor, rewards: Tensor, *, order: int = 32,
    reduction: str = "mean",
) -> Tensor:
    """Exact negative finite-order TailRL objective for fixed action rewards.

    Implements arxiv.org/html/2609.02987v1 Eq. 23/25: integrate
    ``sum((1 - P(reward > threshold))**k / k, k=1..order)`` over [0, 1].
    Rewards are detached, legal action qualities, not normalized policy targets.
    Illegal reward/logit values are ignored; legal rewards must be finite [0, 1].

    Sorting gives exact interval widths, including ties and the constant
    ``(1 - max_reward) * H_order`` above the attainable reward range. There is
    no per-row reward rescaling or omission of zero-tail intervals. Order 1 is
    ``1 - E[reward]``. This enumerates known action rewards; it does not sample
    the paper's rollout estimator or equate independent samples with MCTS.

    Work is O(B*A*log(A) + order*B*A), with no [B,A,A] event tensor. Autograd
    retains O(order*B*A) polynomial intermediates. Low precision inputs use
    float32 work, as in ``legal_log_probs``. Reduction is mean, sum, or none.
    """
    if type(order) is not int or order < 1:
        raise ValueError("order must be a positive integer")
    if reduction not in ("mean", "sum", "none"):
        raise ValueError("reduction must be mean, sum, or none")
    logp = legal_log_probs(logits, legal)
    if (
        rewards.shape != logits.shape or rewards.device != logits.device
        or not rewards.is_floating_point()
    ):
        raise ValueError("rewards must be floating point with logits' shape/device")
    valid_rewards = rewards.masked_select(legal)
    if not bool((torch.isfinite(valid_rewards) & (valid_rewards >= 0)
                 & (valid_rewards <= 1)).all()):
        raise ValueError("legal rewards must be finite and in [0, 1]")
    values, indices = rewards.detach().to(logp.dtype).masked_fill(~legal, 0).sort(-1)
    probabilities = logp.exp().gather(-1, indices)
    cdf = probabilities.cumsum(-1)
    # The final interval has exactly zero success probability. Make its loss
    # policy-independent, including for rows where all rewards are equal.
    cdf = torch.cat((cdf[:, :-1].clamp(0, 1), torch.ones_like(cdf[:, -1:])), -1)
    widths = torch.cat((values[:, 1:], torch.ones_like(values[:, -1:])), -1) - values
    # Horner evaluation of F + F**2/2 + ... + F**order/order. No log(0),
    # divisions by small tail probabilities, or order-by-action broadcast.
    polynomial = torch.zeros_like(cdf)
    for k in range(order, 0, -1):
        polynomial = cdf * (polynomial + 1.0 / k)
    per_row = (widths * polynomial).sum(-1)
    if reduction == "none":
        return per_row
    return per_row.mean() if reduction == "mean" else per_row.sum()


def _mean(values: Tensor) -> float | None:
    return float(values.double().mean()) if values.numel() else None


@torch.no_grad()
def compare_policies(
    reference: Tensor, candidate: Tensor, target: Tensor, legal: Tensor,
    *, cohort: Tensor | None = None, spec: TailCohort = TailCohort(),
    budgets: tuple[int, ...] = (1, 8, 32, 128, 512),
) -> tuple[dict[str, Any], dict[str, Tensor]]:
    """Paired point estimates plus per-row observations for later clustering.

    Both union-tail mass and per-action retention are reported: a union loss
    can sacrifice one good move while increasing another. No strength verdict
    or independent-position confidence interval is manufactured here.
    """
    if reference.shape != candidate.shape:
        raise ValueError("reference and candidate shapes differ")
    if not budgets or any(type(n) is not int or n < 1 for n in budgets):
        raise ValueError("iid sampling budgets must be positive integers")
    # Diagnostic precision, unlike the differentiable training helper.
    base = legal_log_probs(reference.double(), legal)
    cand = legal_log_probs(candidate.double(), legal)
    q = normalized_target(target.double(), legal)
    fixed = freeze_cohort(reference, q, legal, spec) if cohort is None else cohort
    if fixed.shape != legal.shape or fixed.dtype != torch.bool:
        raise ValueError("cohort must be boolean [B, A]")
    base_mass, valid = tail_log_mass(base, legal, fixed[:, None, :])
    cand_mass, _ = tail_log_mass(cand, legal, fixed[:, None, :])
    rows = valid[:, 0]
    base_mass, cand_mass = base_mass[:, 0], cand_mass[:, 0]
    base_safe, cand_safe = base.masked_fill(~legal, 0), cand.masked_fill(~legal, 0)
    base_ce, cand_ce = -(q * base_safe).sum(-1), -(q * cand_safe).sum(-1)
    action_delta = (cand - base).masked_select(fixed)
    row_delta = cand_mass - base_mass
    report: dict[str, Any] = {
        "cohort_spec": asdict(spec), "rows": int(reference.shape[0]),
        "rare_rows": int(rows.sum()), "rare_actions": int(fixed.sum()),
        "cohort_status": "observed" if bool(rows.any()) else "empty_not_evidence_of_no_problem",
        "reference_target_ce": _mean(base_ce), "candidate_target_ce": _mean(cand_ce),
        "target_ce_delta": _mean(cand_ce - base_ce),
        "reference_entropy": _mean(-(base.exp() * base_safe).sum(-1)),
        "candidate_entropy": _mean(-(cand.exp() * cand_safe).sum(-1)),
        "reference_rare_mass": _mean(base_mass[rows].exp()),
        "candidate_rare_mass": _mean(cand_mass[rows].exp()),
        "rare_log_mass_delta": _mean(row_delta[rows]),
        "rare_action_logp_delta": _mean(action_delta),
        "rare_action_drop_10x_fraction": _mean((action_delta <= -math.log(10)).double()),
        "rare_action_drop_100x_fraction": _mean((action_delta <= -math.log(100)).double()),
    }
    iid: dict[str, Any] = {}
    for n in budgets:
        # Independent samples WITH replacement, NOT Gumbel/MCTS simulations.
        entry = {}
        for name, logs in (("reference", base_mass[rows]), ("candidate", cand_mass[rows])):
            p = logs.exp().clamp(0, 1)
            entry[name] = _mean(-torch.expm1(n * torch.log1p(-p)))
        iid[str(n)] = entry
    report["iid_any_cohort_move_probability_not_mcts"] = iid
    per_row = {
        "cohort": fixed, "eligible": rows,
        "reference_ce": base_ce, "candidate_ce": cand_ce,
        "reference_log_mass": base_mass, "candidate_log_mass": cand_mass,
    }
    return report, per_row
