/*
 * Real DeepFin CUDA AOTInductor parity bridge.
 *
 * Inputs are generated by run_parity.py through the existing CBoard encoder and
 * written as BF16 bit patterns. This executable does not embed Python: it reads
 * the fixture, creates a CUDA BF16 tensor, runs AOTIModelPackageLoader, expands
 * compact policy output to DeepFin's dense 4672 search-policy semantics, and
 * returns only compact scalar summaries to Bend.
 */

#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <exception>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <vector>

#include <torch/torch.h>
#include <torch/csrc/inductor/aoti_package/model_package_loader.h>

namespace {

constexpr char kMagic[8] = {'D','F','C','U','D','A','3','\0'};
constexpr uint32_t kVersion = 1;
constexpr float kIllegalPolicyLogit = -1.0e9f;

struct Fixture {
  uint32_t batch = 0;
  uint32_t planes = 0;
  uint32_t full_policy_width = 0;
  std::vector<uint32_t> compact_to_full;
  std::vector<uint16_t> input_bf16;
};

bool read_exact(std::ifstream& in, void* dst, size_t bytes) {
  in.read(static_cast<char*>(dst), static_cast<std::streamsize>(bytes));
  return static_cast<size_t>(in.gcount()) == bytes;
}

bool read_u32(std::ifstream& in, uint32_t* out) {
  uint8_t bytes[4];
  if (!read_exact(in, bytes, sizeof(bytes))) return false;
  *out = static_cast<uint32_t>(bytes[0])
       | (static_cast<uint32_t>(bytes[1]) << 8)
       | (static_cast<uint32_t>(bytes[2]) << 16)
       | (static_cast<uint32_t>(bytes[3]) << 24);
  return true;
}

bool read_u16(std::ifstream& in, uint16_t* out) {
  uint8_t bytes[2];
  if (!read_exact(in, bytes, sizeof(bytes))) return false;
  *out = static_cast<uint16_t>(
    static_cast<uint16_t>(bytes[0])
    | (static_cast<uint16_t>(bytes[1]) << 8)
  );
  return true;
}

bool load_fixture(const std::string& path, Fixture* fixture) {
  std::ifstream in(path, std::ios::binary);
  if (!in) {
    std::cerr << "cannot open CUDA parity fixture: " << path << "\n";
    return false;
  }

  char magic[8];
  if (!read_exact(in, magic, sizeof(magic))
      || std::memcmp(magic, kMagic, sizeof(kMagic)) != 0) {
    std::cerr << "invalid CUDA parity fixture magic\n";
    return false;
  }

  uint32_t version = 0;
  uint32_t map_count = 0;
  if (!read_u32(in, &version)
      || !read_u32(in, &fixture->batch)
      || !read_u32(in, &fixture->planes)
      || !read_u32(in, &fixture->full_policy_width)
      || !read_u32(in, &map_count)) {
    std::cerr << "truncated CUDA parity fixture header\n";
    return false;
  }
  if (version != kVersion || fixture->batch == 0 || fixture->planes == 0
      || fixture->full_policy_width == 0) {
    std::cerr << "invalid CUDA parity fixture header\n";
    return false;
  }

  fixture->compact_to_full.resize(map_count);
  for (uint32_t i = 0; i < map_count; ++i) {
    if (!read_u32(in, &fixture->compact_to_full[i])) {
      std::cerr << "truncated CUDA parity policy map\n";
      return false;
    }
    if (fixture->compact_to_full[i] >= fixture->full_policy_width) {
      std::cerr << "CUDA parity policy map index out of range\n";
      return false;
    }
  }

  const uint64_t input_count =
      static_cast<uint64_t>(fixture->batch)
      * static_cast<uint64_t>(fixture->planes) * 64u;
  if (input_count > static_cast<uint64_t>(SIZE_MAX / sizeof(uint16_t))) {
    std::cerr << "CUDA parity fixture input is too large\n";
    return false;
  }

  fixture->input_bf16.resize(static_cast<size_t>(input_count));
  for (size_t i = 0; i < fixture->input_bf16.size(); ++i) {
    if (!read_u16(in, &fixture->input_bf16[i])) {
      std::cerr << "truncated CUDA parity input tensor\n";
      return false;
    }
  }
  return true;
}

uint32_t env_device_index() {
  const char* raw = std::getenv("DEEPFIN_AOTI_DEVICE_INDEX");
  if (raw == nullptr || raw[0] == '\0') return 0;
  char* end = nullptr;
  unsigned long value = std::strtoul(raw, &end, 10);
  if (end == raw || *end != '\0' || value > 0x7fffffffUL) {
    throw std::runtime_error("invalid DEEPFIN_AOTI_DEVICE_INDEX");
  }
  return static_cast<uint32_t>(value);
}

std::vector<float> decode_bf16(const std::vector<uint16_t>& bits) {
  std::vector<float> out(bits.size());
  for (size_t i = 0; i < bits.size(); ++i) {
    uint32_t word = static_cast<uint32_t>(bits[i]) << 16;
    std::memcpy(&out[i], &word, sizeof(word));
  }
  return out;
}

at::Tensor find_wdl(const std::vector<at::Tensor>& outputs) {
  for (const auto& out : outputs) {
    if (out.dim() == 2 && out.size(1) == 3) return out;
  }
  return {};
}

at::Tensor find_policy(const std::vector<at::Tensor>& outputs) {
  for (const auto& out : outputs) {
    if (out.dim() == 2 && out.size(1) != 3) return out;
  }
  return {};
}

at::Tensor dense_policy(
  const at::Tensor& raw_policy,
  const Fixture& fixture
) {
  const int64_t raw_width = raw_policy.size(1);
  if (raw_width == static_cast<int64_t>(fixture.full_policy_width)) {
    return raw_policy;
  }
  if (raw_width != static_cast<int64_t>(fixture.compact_to_full.size())) {
    throw std::runtime_error(
      "package policy width does not match dense width or compact map"
    );
  }

  std::vector<int64_t> map64(fixture.compact_to_full.begin(),
                             fixture.compact_to_full.end());
  auto map_cpu = torch::from_blob(
    map64.data(),
    {static_cast<int64_t>(map64.size())},
    torch::TensorOptions().dtype(torch::kInt64).device(torch::kCPU)
  ).clone();
  auto map_device = map_cpu.to(raw_policy.device());

  auto dense = torch::full(
    {raw_policy.size(0), static_cast<int64_t>(fixture.full_policy_width)},
    kIllegalPolicyLogit,
    raw_policy.options()
  );
  dense.index_copy_(1, map_device, raw_policy);
  return dense;
}

struct BitsSummary {
  uint32_t count = 0;
  uint32_t xors = 0;
  uint32_t mix = 0;
};

BitsSummary summarize_f32(const at::Tensor& tensor) {
  at::Tensor cpu = tensor.to(torch::kCPU, torch::kFloat32).contiguous();
  const int64_t n = cpu.numel();
  if (n < 0 || static_cast<uint64_t>(n) > 0xffffffffULL) {
    throw std::runtime_error("summary tensor too large");
  }

  BitsSummary out;
  out.count = static_cast<uint32_t>(n);
  const float* values = cpu.data_ptr<float>();
  uint32_t mix = 0;
  uint32_t xors = 0;
  for (uint32_t i = 0; i < out.count; ++i) {
    uint32_t bits = 0;
    std::memcpy(&bits, &values[i], sizeof(bits));
    xors ^= bits;
    mix += static_cast<uint32_t>(
      static_cast<uint64_t>(bits) * static_cast<uint64_t>(i + 1)
    );
  }
  out.xors = xors;
  out.mix = mix;
  return out;
}

}  // namespace

extern "C" uint32_t deepfin_cuda_parity_run(
  uint32_t* out,
  uint32_t capacity
) {
  if (out == nullptr || capacity < 8) return 0;

  const char* package_path = std::getenv("DEEPFIN_AOTI_CUDA_PACKAGE");
  const char* fixture_path = std::getenv("DEEPFIN_AOTI_CUDA_FIXTURE");
  if (package_path == nullptr || package_path[0] == '\0'
      || fixture_path == nullptr || fixture_path[0] == '\0') {
    std::cerr << "DEEPFIN_AOTI_CUDA_PACKAGE and DEEPFIN_AOTI_CUDA_FIXTURE "
                 "must be set\n";
    return 0;
  }

  try {
    Fixture fixture;
    if (!load_fixture(fixture_path, &fixture)) return 0;

    const uint32_t device_index = env_device_index();
    c10::InferenceMode mode;
    torch::inductor::AOTIModelPackageLoader loader(
      package_path, "model", false, 1,
      static_cast<c10::DeviceIndex>(device_index)
    );

    std::vector<float> decoded = decode_bf16(fixture.input_bf16);
    auto cpu = torch::from_blob(
      decoded.data(),
      {
        static_cast<int64_t>(fixture.batch),
        static_cast<int64_t>(fixture.planes),
        8,
        8
      },
      torch::TensorOptions().dtype(torch::kFloat32).device(torch::kCPU)
    ).clone().to(torch::kBFloat16);

    const c10::Device device(torch::kCUDA, static_cast<c10::DeviceIndex>(device_index));
    at::Tensor input = cpu.to(device);

    std::vector<at::Tensor> outputs = loader.run({input});
    at::Tensor raw_policy = find_policy(outputs);
    at::Tensor wdl = find_wdl(outputs);
    if (!raw_policy.defined() || !wdl.defined()) {
      throw std::runtime_error("could not identify policy and WDL package outputs");
    }
    if (raw_policy.size(0) != static_cast<int64_t>(fixture.batch)
        || wdl.size(0) != static_cast<int64_t>(fixture.batch)) {
      throw std::runtime_error("package output batch does not match fixture");
    }

    const uint32_t raw_width = static_cast<uint32_t>(raw_policy.size(1));
    BitsSummary policy_summary = summarize_f32(dense_policy(raw_policy, fixture));
    BitsSummary wdl_summary = summarize_f32(wdl);

    out[0] = fixture.batch;
    out[1] = raw_width;
    out[2] = policy_summary.count;
    out[3] = policy_summary.xors;
    out[4] = policy_summary.mix;
    out[5] = wdl_summary.count;
    out[6] = wdl_summary.xors;
    out[7] = wdl_summary.mix;
    return 8;
  } catch (const std::exception& exc) {
    std::cerr << "DeepFin CUDA parity failed: " << exc.what() << "\n";
    return 0;
  }
}
