from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

def encode_piece_planes(
    bitboards: NDArray[np.uint64],
    turns: NDArray[np.int32],
    n_steps: int,
) -> NDArray[np.float32]: ...

def legal_move_policy_indices(
    us_p: int, us_n: int, us_b: int, us_r: int, us_q: int, us_k: int,
    th_p: int, th_n: int, th_b: int, th_r: int, th_q: int, th_k: int,
    turn: int,
    ck: int, cq: int, tk: int, tq: int,
    ep: int,
) -> NDArray[np.int32]: ...

class CBoard:
    # Properties
    @property
    def turn(self) -> int: ...
    @property
    def ep_square(self) -> int: ...
    @property
    def halfmove_clock(self) -> int: ...
    @property
    def castling(self) -> int: ...
    @property
    def pawns(self) -> int: ...
    @property
    def knights(self) -> int: ...
    @property
    def bishops(self) -> int: ...
    @property
    def rooks(self) -> int: ...
    @property
    def queens(self) -> int: ...
    @property
    def kings(self) -> int: ...
    @property
    def occ_white(self) -> int: ...
    @property
    def occ_black(self) -> int: ...
    @property
    def zobrist_hash(self) -> int: ...
    @property
    def hist_len(self) -> int: ...
    @property
    def hash_stack_len(self) -> int: ...
    @property
    def ply(self) -> int: ...

    @classmethod
    def from_board(cls, board: object) -> CBoard: ...
    @classmethod
    def from_raw(
        cls,
        pawns: int, knights: int, bishops: int,
        rooks: int, queens: int, kings: int,
        occ_white: int, occ_black: int,
        turn: int, castling: int, ep_square: int, halfmove_clock: int,
    ) -> CBoard: ...

    def copy(self) -> CBoard: ...
    def push_index(self, policy_index: int) -> None: ...
    def is_game_over(self) -> bool: ...
    def terminal_value(self) -> float: ...
    def legal_move_indices(self) -> NDArray[np.int32]: ...
    def fen(self) -> str: ...
    def result(self) -> str: ...
    def is_checkmate(self) -> bool: ...
    def is_stalemate(self) -> bool: ...
    def encode_planes(self) -> NDArray[np.float32]: ...
    def encode_146(self) -> NDArray[np.float32]: ...
    def encode_146_and_legal(self) -> tuple[NDArray[np.float32], NDArray[np.int32]]: ...
