// Build-time binding only. The deployed binary does not parse JSON or run JS/Python.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const digest = x => typeof x === 'string' && /^[a-f0-9]{64}$/.test(x);
export function validateBinding(m, packageHash) {
  if (!m || typeof m !== 'object' || Array.isArray(m)
      || m.format !== 'deepfin-tuple-policy-wdl-checkpoint-v3'
      || m.sha256 !== packageHash || !digest(m.sha256) || !digest(m.checkpoint_sha256)
      || !['model', 'swa_model'].includes(m.weights_key)
      || m.batch !== 1 || m.policy_width !== 1858 || m.row_independent !== true
      || m.device !== 'cpu' || m.device_index !== 0 || m.dtype !== 'float32'
      || m.history_rep_fix !== true
      || !['lc0_root', 'lc0_root_legacy_meta'].includes(m.input_history_encoding)
      || !['v1', 'v2_threats'].includes(m.input_extra_features)
      || m.channels !== (m.input_extra_features === 'v1' ? 146 : 175)
      || typeof m.torch_version !== 'string' || !/^\d+\.\d+\.\d+(?:\+cpu)?$/.test(m.torch_version)) {
    throw new Error('unsupported or mismatched model binding; require exact v3 CPU F32 batch-one compact-policy package and corrected root encoding');
  }
  const cfg = m.resolved_model_config;
  if (!cfg || cfg.input_history_encoding !== m.input_history_encoding
      || cfg.input_extra_features !== m.input_extra_features || cfg.history_rep_fix !== true
      || cfg.policy_encoding !== 'lc0_1858') {
    throw new Error('resolved model encoding does not agree with package contract');
  }
  return Object.freeze({ package_sha256: m.sha256, checkpoint_sha256: m.checkpoint_sha256,
    torch_version: m.torch_version.split('+')[0], channels: m.channels, batch: 1,
    profile: (m.channels === 146 ? 1 : 3) + Number(m.input_history_encoding === 'lc0_root_legacy_meta'),
    weights_key: m.weights_key });
}
// Backend-only binding. The UCI build still goes through the singleton gate.
export function validateBatchBinding(m, packageHash) {
  if (!m || ![1, 2, 4, 8, 16].includes(m.batch))
    throw new Error('unsupported native fixed batch; expected 1, 2, 4, 8 or 16');
  const b = validateBinding({ ...m, batch: 1 }, packageHash);
  return Object.freeze({ ...b, batch: m.batch });
}
// Deliberately separate from both CPU gates: merely passing a CUDA sidecar to
// the old entrypoints must never enable a new execution mode.
export function validateCudaBatchBinding(m, packageHash) {
  if (!m || typeof m !== 'object' || Array.isArray(m)
      || m.device !== 'cuda' || m.dtype !== 'bfloat16'
      || !Number.isInteger(m.device_index) || m.device_index < 0 || m.device_index > 127
      || typeof m.torch_version !== 'string' || !/^\d+\.\d+\.\d+\+cu\d{3}$/.test(m.torch_version)) {
    throw new Error('CUDA binding requires explicit CUDA BF16, device index and release CUDA Torch build');
  }
  const [release, build] = m.torch_version.split('+cu');
  const version = Number(build);
  if (version < 110) throw new Error('CUDA BF16 requires CUDA 11 or newer');
  // Reuse the exact hash, batch and encoding checks only AFTER checking all
  // original target fields above. Never mutate or relabel the supplied package.
  const b = validateBatchBinding({ ...m, device: 'cpu', device_index: 0,
    dtype: 'float32', torch_version: release }, packageHash);
  return Object.freeze({ ...b, device: 'cuda', dtype: 'bfloat16', device_index: m.device_index,
    cuda_runtime_version: Math.floor(version / 10) * 1000 + (version % 10) * 10 });
}
export function bindingHeader(b) {
  return '// Exact trusted package binding; autogenerated at build time, never committed.\n' +
    Object.entries({ DEEPFIN_MODEL_SHA256: b.package_sha256, DEEPFIN_CHECKPOINT_SHA256: b.checkpoint_sha256,
      DEEPFIN_MODEL_TORCH_VERSION: b.torch_version, DEEPFIN_MODEL_CHANNELS: b.channels,
      DEEPFIN_MODEL_PROFILE: b.profile, DEEPFIN_MODEL_BATCH: b.batch,
      DEEPFIN_MODEL_CUDA: Number(b.device === 'cuda'), DEEPFIN_MODEL_DEVICE_INDEX: b.device_index ?? 0,
      DEEPFIN_MODEL_CUDA_RUNTIME: b.cuda_runtime_version ?? 0 })
      .map(([k, v]) => `#define ${k} ${JSON.stringify(v)}\n`).join('');
}
export function bind(packagePath, batchBackend = false, cudaBackend = false) {
  const path = resolve(packagePath);
  if (!path.endsWith('.pt2')) throw new Error('expected a .pt2 package');
  const manifest = JSON.parse(readFileSync(path.slice(0, -4) + '.json', 'utf8'));
  if (cudaBackend && !batchBackend) throw new Error('CUDA is backend-only, not a singleton UCI binding');
  const validate = cudaBackend ? validateCudaBatchBinding : batchBackend ? validateBatchBinding : validateBinding;
  return validate(manifest, createHash('sha256').update(readFileSync(path)).digest('hex'));
}
if (import.meta.main) {
  const [mode, packagePath, header, ...extra] = process.argv.slice(2);
  const check = ['--check', '--batch-check', '--cuda-batch-check'].includes(mode);
  const write = ['--header', '--batch-header', '--cuda-batch-header'].includes(mode);
  if (!packagePath || extra.length || (!check && !write)
      || (check && header) || (write && !header)) {
    throw new Error('usage: bind_model.js --check|--batch-check|--cuda-batch-check PACKAGE.pt2 | --header|--batch-header|--cuda-batch-header PACKAGE.pt2 NEW_HEADER');
  }
  const b = bind(packagePath, mode.includes('-batch-'), mode.startsWith('--cuda-'));
  if (header) writeFileSync(header, bindingHeader(b), { flag: 'wx' });
  console.log(JSON.stringify(b));
}
